name: Run Regression Tests with Allure

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  regression-tests:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: 3.11

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Clean and run pytest with regression marker
      run: |
        rm -rf allure-results
        pytest -m regression --alluredir=allure-results


    - name: Generate Allure HTML Report
      run: |
        wget https://github.com/allure-framework/allure2/releases/download/2.24.1/allure-2.24.1.tgz
        tar -xvzf allure-2.24.1.tgz
        ./allure-2.24.1/bin/allure generate allure-results --clean -o allure-report

    - name: Upload Allure HTML Report as Artifact
      uses: actions/upload-artifact@v4
      with:
        name: allure-report
        path: allure-report
